const uiPreset = require('./preset/preset')

module.exports = {
  darkMode: 'class',
  presets: [require('@medusajs/ui-preset'), uiPreset],
  content: [
    './src/app/**/*.{js,ts,jsx,tsx}',
    './src/pages/**/*.{js,ts,jsx,tsx}',
    './src/components/**/*.{js,ts,jsx,tsx}',
    './src/modules/**/*.{js,ts,jsx,tsx}',
    './node_modules/@medusajs/ui/dist/**/*.{js,jsx,ts,tsx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        headline: ['var(--font-noto-serif)', 'Georgia', 'serif'],
        body: ['var(--font-plus-jakarta)', 'sans-serif'],
        label: ['var(--font-plus-jakarta)', 'sans-serif'],
      },
      colors: {
        // Material Design 3 warm earthy palette (product detail)
        primary: '#6f4627',
        'on-primary': '#ffffff',
        'primary-container': '#8b5e3c',
        'primary-fixed': '#ffdcc5',
        'primary-fixed-dim': '#f4bb92',
        'inverse-primary': '#f4bb92',
        secondary: '#586330',
        'on-secondary': '#ffffff',
        'secondary-container': '#d8e6a6',
        'on-secondary-container': '#5c6834',
        tertiary: '#7d4000',
        'tertiary-container': '#9f550c',
        'on-tertiary-container': '#ffe3d1',
        'tertiary-fixed': '#ffdcc4',
        'tertiary-fixed-dim': '#ffb781',
        surface: '#fcf9f4',
        'surface-dim': '#dcdad5',
        'surface-bright': '#fcf9f4',
        'surface-variant': '#e5e2dd',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f6f3ee',
        'surface-container': '#f0ede8',
        'surface-container-high': '#ebe8e3',
        'surface-container-highest': '#e5e2dd',
        'surface-tint': '#805533',
        'on-surface': '#1c1c19',
        'on-surface-variant': '#51443c',
        'inverse-surface': '#31302d',
        'inverse-on-surface': '#f3f0eb',
        outline: '#83746b',
        'outline-variant': '#d5c3b8',
        'surface-bg': '#fcf9f4',
      },
      transitionProperty: {
        width: 'width margin',
        height: 'height',
        bg: 'background-color',
        display: 'display opacity',
        visibility: 'visibility',
        padding: 'padding-top padding-right padding-bottom padding-left',
      },
      keyframes: {
        ring: { '0%': { transform: 'rotate(0deg)' }, '100%': { transform: 'rotate(360deg)' } },
        'fade-in-right': { '0%': { opacity: '0', transform: 'translateX(10px)' }, '100%': { opacity: '1', transform: 'translateX(0)' } },
        'fade-in-top': { '0%': { opacity: '0', transform: 'translateY(-10px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        'fade-out-top': { '0%': { height: '100%' }, '99%': { height: '0' }, '100%': { visibility: 'hidden' } },
        'accordion-slide-up': { '0%': { height: 'var(--radix-accordion-content-height)', opacity: '1' }, '100%': { height: '0', opacity: '0' } },
        'accordion-slide-down': { '0%': { 'min-height': '0', 'max-height': '0', opacity: '0' }, '100%': { 'min-height': 'var(--radix-accordion-content-height)', 'max-height': 'none', opacity: '1' } },
        enter: { '0%': { transform: 'scale(0.9)', opacity: 0 }, '100%': { transform: 'scale(1)', opacity: 1 } },
        leave: { '0%': { transform: 'scale(1)', opacity: 1 }, '100%': { transform: 'scale(0.9)', opacity: 0 } },
        'slide-in': { '0%': { transform: 'translateY(-100%)' }, '100%': { transform: 'translateY(0)' } },
      },
      animation: {
        ring: 'ring 2.2s cubic-bezier(0.5, 0, 0.5, 1) infinite',
        'fade-in-right': 'fade-in-right 0.3s cubic-bezier(0.5, 0, 0.5, 1) forwards',
        'fade-in-top': 'fade-in-top 0.2s cubic-bezier(0.5, 0, 0.5, 1) forwards',
        'fade-out-top': 'fade-out-top 0.2s cubic-bezier(0.5, 0, 0.5, 1) forwards',
        'accordion-open': 'accordion-slide-down 300ms cubic-bezier(0.87, 0, 0.13, 1) forwards',
        'accordion-close': 'accordion-slide-up 300ms cubic-bezier(0.87, 0, 0.13, 1) forwards',
        enter: 'enter 200ms ease-out',
        'slide-in': 'slide-in 1.2s cubic-bezier(.41,.73,.51,1.02)',
        leave: 'leave 150ms ease-in forwards',
      },
    },
  },
  plugins: [require('tailwindcss-radix')()],
}
